### PR TITLE
Add smoltcp trophies

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks!

bors r+

**Comment by frewsxcv** [comment]
Cc @notriddle

**Comment by frewsxcv** [comment]
In retrospect, I don't remember if I enabled bors reviewers for this repo

**Comment by notriddle** [comment]
You didn't enable bors on this repo, and you don't have anything in here that it'll recognize as a CI system.

**Comment by frewsxcv** [comment]
Yeah, sorry about that. Realized that right after I sent it

**Pull request merged**
